### ISSUE TITLE
Ubuntu package is not starting the service after install

### ISSUE THREAD

**Issue by apkar** [FoundationDB/fdb-document-layer#32]
The issue is reported on [forums](https://forums.foundationdb.org/t/how-to-connect-to-foundationdb-with-mongodb-cli/977). I also tried this on 16.04, same issue there as well.

**Comment by dongxinEric** [comment]
So the reason why it failed to start the service after install the DEB installer on Ubuntu is that `invoke-rc.d` failed. The fix is simply change it to the more recommended way to start a service nowadays, using `/etc/init.d/fdb-document-layer start`. ***This is also how we start FDB KVS services in the FDB DEB installers.***
