### ISSUE TITLE
Update commands from mongo-go-driver are failing

### ISSUE THREAD

**Issue by nomoonx** [FoundationDB/fdb-document-layer#34]
the mongo driver I'm using: https://github.com/mongodb/mongo-go-driver

The UpdateOne and UpdateMany functions work with MongoDB itself but not with fdb-doc. 

The error I got is ` command failure: {"errmsg": "command [update] failed with err: An unknown error occurred","bad cmd": "{ update: \"clickdata\", updates: [ { q: { auction_id_with_imp_index: \"hohololiiii\" }, u: { $set: {abc: \"aaa\" } }, multi: false } ] }","ok": {"$numberInt":"0"}}`

The only update function I can make it work is the FindOneAndUpdate function, but that function will always return something even the update didn't work.

**Comment by apkar** [comment]
#36 should address the specific problem you are facing.

mongo-go-driver still wouldn't work with Document Layer, though. Document Layer is now only compatible with MongoDB server version 3.0. Go driver is compatible with versions >= 3.2. Irrespective of the server version, Go driver seems to use the `find` command to send queries. `find` command is supported since 3.2. So, you will see issues when you try to run queries. Issue #11, should address that.

Until then, I suggest using mgo driver.
